name: github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install sphinx
        run: |
          sudo apt-get install python3-sphinx

      - name: Build docs
        run: |
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd docs/
          make html
          cp -r _build/* ../gh-pages/

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gh-pages
